### ISSUE TITLE
Would you consider using Github pages to better show your project?

### ISSUE THREAD

**Issue by Gabri432** [dhmunro/phlog#1]
I really like your project. I think it is really interesting. 
Have you ever considered using Github pages to create a website to show the content of this repository?

I personally think by doing so more people could enjoy this project too.

**Comment by dhmunro** [comment]
I haven't yet decided how I want to deploy this.  I recently bought
the domain smootherpebbles.net and you can find a more complicated
piece on how Kepler surveyed the solar system there.  I'll check
out your idea to use github pages to provide a live copy of these
work-in-progress pages - since it is designed for code documentation
I'm not sure how friendly it is to svg files and interactive javascript,
but since everything here is running on client side there's a decent
chance it will work.

Thanks for your interest.

**Comment by dhmunro** [comment]
Okay, I went ahead and turned on the github pages, and it appears to work.  You can see it at dhmunro.github.io/phlog
